"""empty message

Revision ID: 20e9a8e59016
Revises: 05b19e802b84
Create Date: 2020-05-02 18:20:48.809585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e9a8e59016'
down_revision = '05b19e802b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_stockname', table_name='portfolio')
    op.create_index(op.f('ix_portfolio_stockname'), 'portfolio', ['stockname'], unique=False)
    op.drop_index('ix_portfolio_userid', table_name='portfolio')
    op.create_index(op.f('ix_portfolio_userid'), 'portfolio', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_userid'), table_name='portfolio')
    op.create_index('ix_portfolio_userid', 'portfolio', ['userid'], unique=True)
    op.drop_index(op.f('ix_portfolio_stockname'), table_name='portfolio')
    op.create_index('ix_portfolio_stockname', 'portfolio', ['stockname'], unique=True)
    # ### end Alembic commands ###
