"""empty message

Revision ID: f873b9d42ade
Revises: 62dfd8ad795a
Create Date: 2020-05-02 17:43:44.332894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f873b9d42ade'
down_revision = '62dfd8ad795a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('stockname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_stockname'), 'portfolio', ['stockname'], unique=True)
    op.create_index(op.f('ix_portfolio_username'), 'portfolio', ['username'], unique=True)
    op.drop_table('aapl_historical')
    op.drop_table('amzn_historical')
    op.drop_table('coke_historical')
    op.drop_table('nke_historical')
    op.drop_table('aapl_realtime')
    op.drop_table('coke_realtime')
    op.drop_table('sbux_historical')
    op.drop_table('goog_historical')
    op.drop_table('msft_realtime')
    op.drop_table('nke_realtime')
    op.drop_table('ge_historical')
    op.drop_table('msft_historical')
    op.drop_table('sbux_realtime')
    op.drop_table('ge_realtime')
    op.drop_table('amzn_realtime')
    op.drop_table('uber_historical')
    op.drop_table('fb_realtime')
    op.drop_table('uber_realtime')
    op.drop_table('fb_historical')
    op.drop_table('goog_realtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goog_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fb_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('uber_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fb_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('uber_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('amzn_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ge_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sbux_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('msft_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ge_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nke_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('msft_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('goog_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sbux_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coke_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('aapl_realtime',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nke_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coke_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('amzn_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('aapl_historical',
    sa.Column('time', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('open', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('high', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('low', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('close', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('volume', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_portfolio_username'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_stockname'), table_name='portfolio')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
